### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by MarzaElise** [andrewthederp/Disgames#13]
First things first, I'd like to thank Jerry for being cool and taking care of docs, however, i have encountered some minor problems in the docs.
- Typo in FAQ
    - "editing" is typed as "[edditing](https://andrewthederp.github.io/Disgames/faq/#how-do-i-contribute-to-disgames)"
- File name problems
    - file names have no spaces. while having spaces would fuck up the URL and add "%20"s, I'd appreciate it if the file names were changed with `-` in place of spaces.
    - For example, [basicbotsetup.md](https://andrewthederp.github.io/Disgames/setups/basicbotsetup/) could probably be named as `basic-bot-setup.md`.
    - Same goes with [advancedbotsetup.md](https://andrewthederp.github.io/Disgames/setups/advancedbotsetup/), it could be named as advanced-bot-setup.md
- I would also love the link in [basicbotsetup](https://andrewthederp.github.io/Disgames/setups/basicbotsetup/) (for the guide) to be changed into https://discordpy.readthedocs.io/en/latest/discord.html
- And the example installation snippet to be changed into `py -3 -m pip install discord.py disgames`. This was initially made to be used with discord.py and will stay as it is until we provide support for other libs as well.

Everything else seems good enough <3

**Comment by Jerry-py** [comment]
Alr fixed? in https://github.com/andrewthederp/Disgames/pull/12?

**Comment by MarzaElise** [comment]
:+1:
