### ISSUE TITLE
This appeared when I tried bot.load_extension("disgames")

### ISSUE THREAD

**Issue by KafkaOnTheMoon** [andrewthederp/Disgames#6]
![image](https://user-images.githubusercontent.com/91415390/140740953-9885b7b2-54d8-4196-b4d2-5242fb78e730.png)

**Comment by MarzaElise** [comment]
are you sure you are at the latest version?

**Comment by MarzaElise** [comment]
fuck i accidentally closed lel

**Comment by MarzaElise** [comment]
I literally ran the code in examples/load_extension.py and it seems to be working fine

![image](https://user-images.githubusercontent.com/77537491/140749671-44720c21-5b24-4b1b-83b1-114cc8dc6777.png)

**Comment by KafkaOnTheMoon** [comment]
no im sure it didnt work

**Comment by MarzaElise** [comment]
> are you sure you are at the latest version?

@GoddessLena

**Comment by MarzaElise** [comment]
this was already fixed in #4  tho
