### ISSUE TITLE
Chess game with another player

### ISSUE THREAD

**Issue by KafkaOnTheMoon** [andrewthederp/Disgames#7]
I tried playing chess with my friend since I can't play with the AI. After my turn it should be his turn, right? But for some reason, it's still MY turn. Can you guys fix this? The chess pieces on the board clearly are working fine. 
Also what I mean by "still MY turn" is that I also control the black chess pieces.

**Comment by KafkaOnTheMoon** [comment]
It also only shows that it's my turn.

**Comment by MarzaElise** [comment]
@GoddessLena are you *still* having this issue?

**Comment by andrewthederp** [comment]
Fixed, turns will cycle correctly now
